name: Deploy ke VM dengan Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      
      - name: Copy index.html ke folder tmp in server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "./*"
          target: "/home/explore"

      - name: Copy index.html to nginx folder
        uses: appleboy/ssh-action@v1
        with: 
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/explore
            docker build -t ci-cd-image:latest .
            docker rm -f ci-cd-container || true
            docker run -d --name ci-cd-container -p 80:80 ci-cd-image
